kind: pipeline
type: docker
name: default

workspace:
  path: /srv/laravel

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    cache_from: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack

- name: install
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  commands:
    - local-php-security-checker
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - composer format -- --dry-run
    - composer analyse
    - composer test

image_pull_secrets:
  - dockerconfig
