kind: pipeline
type: docker
name: default

workspace:
  path: /srv/laravel

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    cache_from: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    dockerfile: 'docker/Dockerfile'

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules
      - ./vendor

- name: assets
  image: node:14-alpine
  commands:
    - yarn && yarn lint && yarn build

- name: build
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  commands:
    - local-php-security-checker
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - composer format -- --dry-run
    - composer analyse
    - docker-php-ext-enable xdebug && export XDEBUG_MODE=coverage
    - composer test

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
      - ./vendor

- name: deploy
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack-app
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password

image_pull_secrets:
  - dockerconfig

volumes:
  - name: cache
    host:
      path: /tmp/cache
