kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password

trigger:
  event:
  - push
  - pull_request
