kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    cache_from: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack

- name: install
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  commands:
    - composer install

- name: test
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  commands:
    - php artisan test --coverage --min=90

image_pull_secrets:
  - dockerconfig

trigger:
  event:
  - push
  - pull_request
