kind: pipeline
type: docker
name: build

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./.pnpm-store
    - ./vendor

- name: backend
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  environment:
    APP_DEBUG: 'true'
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: test
    DB_USERNAME: root
  commands:
  - composer install
  - export APP_KEY=$(php artisan --no-ansi key:generate --show)
  - php artisan matice:generate
  - local-php-security-checker
  - composer format -- --dry-run
  - composer analyse
  - sleep 10 # Wait for MySQL service starting
  - composer test
  depends_on:
  - restore-cache

- name: frontend
  image: node:14-buster
  commands:
  - curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm i && pnpm lint && pnpm build
  depends_on:
  - restore-cache

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./.pnpm-store
    - ./vendor
  depends_on:
  - frontend
  - backend

- name: image
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack-app
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  depends_on:
  - rebuild-cache

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: front.okami101.io
    port: 2222
    username: okami
    key:
      from_secret: swarm_ssh_key
    script:
    - docker service update --image registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack-app:latest --with-registry-auth laravel-rad-stack_app
  depends_on:
  - image

image_pull_secrets:
- dockerconfig

volumes:
- name: cache
  host:
    path: /tmp/cache

services:
- name: db
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test

trigger:
  event:
  - push
  - pull_request

---

kind: pipeline
type: docker
name: image

steps:

- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    cache_from: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    dockerfile: docker/Dockerfile
    context: docker

trigger:
  event:
  - promote
  target:
  - image
