kind: pipeline
type: docker
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    cache_from: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
    dockerfile: 'docker/Dockerfile'
    context: 'docker'

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./node_modules
    - ./vendor

- name: backend
  image: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack
  commands:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan matice:generate
  - local-php-security-checker
  - composer format -- --dry-run
  - composer analyse
  - export XDEBUG_MODE=coverage
  - composer test

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./node_modules
    - ./vendor

- name: deploy
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack-app
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password

image_pull_secrets:
- dockerconfig

volumes:
- name: cache
  host:
    path: /tmp/cache

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: front.okami101.io
    username: okami
    key:
      from_secret: swarm_ssh_key
    script:
    - docker service update --image registry.okami101.io/adr1enbe4udou1n/laravel-rad-stack-app:latest --with-registry-auth laravel-rad-stack_app

trigger:
  event:
  - promote
  target:
  - production
